export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const ADD_COMMENT_TO_ARTICLE = 'ADD_COMMENT_TO_ARTICLE'

export const CHANGE_DATE_RANGE = 'CHANGE_DATE_RANGE'
export const CHANGE_SELECTION = 'CHANGE_SELECTION'

export const SET_DATA_VALUE = 'SET_DATA_VALUE'
export const ADD_NEW_COMMENT = 'ADD_NEW_COMMENT'
