export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const RESET_RANGE = 'RESET_RANGE'

export const UPDATE_RANGE = 'UPDATE_RANGE'

export const UPDATE_SELECTED = 'UPDATE_SELECTED'

export const FILTER_ARTICLE_BY_NAME = 'FILTER_ARTICLE_BY_NAME'

export const FILTER_ARTICLE_BY_PRIOD = 'FILTER_ARTICLE_BY_PRIOD'